/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BackNextSign(props) {
  const { nodes, materials } = useGLTF('/models-3d/deforestation/back-next-wood-sign.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Sign5">
          <mesh
            name="Cylinder002"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002.geometry}
            material={materials['Light Wood']}
          />
          <mesh
            name="Cylinder002_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_1.geometry}
            material={materials['Dark Wood']}
          />
          <mesh
            name="Cylinder002_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_2.geometry}
            material={materials.Herbs}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/back-next-wood-sign.glb')