/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Text } from '@react-three/drei'
import * as THREE from 'three'

export default function BackNextSign(props) {
  const { nodes, materials } = useGLTF('/models-3d/deforestation/back-next-wood-sign.glb')

  const meshRef = useRef()

  const [dimensions, setDimensions] = useState({ width: 1, height: 1 })

  useEffect(() => {
    if (meshRef.current) {
      // Update dimensions based on the mesh bounding box
      const boundingBox = new THREE.Box3().setFromObject(meshRef.current)
      const size = new THREE.Vector3()
      boundingBox.getSize(size)
      setDimensions({ width: size.x, height: size.y })
    }
  }, [meshRef.current])
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Sign5">
          <mesh
            ref={meshRef}
            name="Cylinder002"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002.geometry}
            material={materials['Light Wood']}
          />
          <mesh
            name="Cylinder002_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_1.geometry}
            material={materials['Dark Wood']}
          />
          <mesh
            name="Cylinder002_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_2.geometry}
            material={materials.Herbs}
          />
        </group>
      </group>
      <Text
        position={[0.05, 1.75, .1]} // Slight offset from surface
        fontSize={dimensions.height * 0.1} // Scale font size relative to sign height
        maxWidth={dimensions.width * 1.7} // Keep text within sign bounds
        textAlign="center"
        anchorX="center"
        anchorY="middle"
        color="#261000"
      >
        {props.textNext}
      </Text>
      <Text
        position={[0.05, 1.65, .1]} // Slight offset from surface
        fontSize={dimensions.height * 0.1} // Scale font size relative to sign height
        maxWidth={dimensions.width * 1.7} // Keep text within sign bounds
        textAlign="center"
        anchorX="center"
        anchorY="middle"
        color="#261000"
      >
        {props.textBack}
      </Text>
    </group>
  )
}

useGLTF.preload('/models-3d/deforestation/back-next-wood-sign.glb')