/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BigIrregularSign(props) {
  const { nodes, materials } = useGLTF('/models-3d/deforestation/big-irregular-wood-sign.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Sign8" rotation={[0, -Math.PI / 2, 0]}>
          <mesh
            name="Cube002"
            castShadow
            receiveShadow
            geometry={nodes.Cube002.geometry}
            material={materials['Dark Wood']}
          />
          <mesh
            name="Cube002_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube002_1.geometry}
            material={materials['Light Wood']}
          />
          <mesh
            name="Cube002_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube002_2.geometry}
            material={materials.Herbs}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/big-irregular-wood-sign.glb')