/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState, useEffect } from 'react'
import { useGLTF, Text } from '@react-three/drei'
import * as THREE from 'three'

export default function BigIrregularSign(props) {
  const { nodes, materials } = useGLTF('/models-3d/deforestation/big-irregular-wood-sign.glb')

  const meshRef = useRef()

  const [dimensions, setDimensions] = useState(null)

  useEffect(() => {
    if (meshRef.current) {
      // Update dimensions based on the mesh bounding box
      const boundingBox = new THREE.Box3().setFromObject(meshRef.current)
      const size = new THREE.Vector3()
      boundingBox.getSize(size)
      setDimensions({ width: size.x, height: size.y })
    }
  }, [meshRef.current])
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Sign8" rotation={[0, -Math.PI / 2, 0]}>
          <mesh
            name="Cube002"
            castShadow
            receiveShadow
            geometry={nodes.Cube002.geometry}
            material={materials['Dark Wood']}
          />
          <mesh
            ref={meshRef}
            name="Cube002_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube002_1.geometry}
            material={materials['Light Wood']}
          />
          <mesh
            name="Cube002_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube002_2.geometry}
            material={materials.Herbs}
          />
        </group>
      </group>
      {dimensions && (<Text
        position={[0.0, 1.81, .1]} // Slight offset from surface
        fontSize={dimensions.height * 0.06} // Scale font size relative to sign height
        maxWidth={dimensions.width * 1.1} // Keep text within sign bounds
        textAlign="center"
        anchorX="center"
        anchorY="middle"
        color="#261000"
      >
        {props.text}
      </Text>)}
    </group>
  )
}

useGLTF.preload('/models-3d/deforestation/big-irregular-wood-sign.glb')