/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function OneWoodSign(props) {
  const { nodes, materials } = useGLTF('/models-3d/deforestation/wood-sign2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Sign11" scale={0.312}>
          <mesh
            name="Cube017"
            castShadow
            receiveShadow
            geometry={nodes.Cube017.geometry}
            material={materials.Herbs}
          />
          <mesh
            name="Cube017_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube017_1.geometry}
            material={materials['Light Wood']}
          />
          <mesh
            name="Cube017_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube017_2.geometry}
            material={materials['Dark Wood']}
          />
          <mesh
            name="Cube017_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube017_3.geometry}
            material={materials.Rocks}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/wood-sign2.glb')