/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState, useEffect } from 'react'
import { useGLTF, Text } from '@react-three/drei'
import * as THREE from 'three'

export default function OneWoodSign(props) {
  const { nodes, materials } = useGLTF('/models-3d/deforestation/wood-sign2.glb')
  const meshRef = useRef()
  const [dimensions, setDimensions] = useState(null)

  useEffect(() => {
    if (meshRef.current) {
      // Update dimensions based on the mesh bounding box
      const boundingBox = new THREE.Box3().setFromObject(meshRef.current)
      const size = new THREE.Vector3()
      boundingBox.getSize(size)
      setDimensions({ width: size.x, height: size.y })
    }
  }, [meshRef.current])

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Sign11" scale={0.312}>
          <mesh
            name="Cube017"
            castShadow
            receiveShadow
            geometry={nodes.Cube017.geometry}
            material={materials.Herbs}
          />
          <mesh
            name="Cube017_1"
            ref={meshRef}
            castShadow
            receiveShadow
            geometry={nodes.Cube017_1.geometry}
            material={materials['Light Wood']}
          />
          <mesh
            name="Cube017_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube017_2.geometry}
            material={materials['Dark Wood']}
          />
          <mesh
            name="Cube017_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube017_3.geometry}
            material={materials.Rocks}
          />
        </group>
      </group>
      {dimensions && ( // Render only when dimensions and center are available
        <Text
          position={[0.05, 1.75, .1]} // Slight offset from surface
          fontSize={dimensions.height * 0.1} // Scale font size relative to sign height
          maxWidth={dimensions.width * 1.7} // Keep text within sign bounds
          textAlign="center"
          anchorX="center"
          anchorY="middle"
          color="#261000"
        >
          {props.text}
        </Text>
      )}
    </group>
  )
}

useGLTF.preload('/models-3d/deforestation/wood-sign2.glb')
