/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function PathsSign(props) {
  const { nodes, materials } = useGLTF('/models-3d/deforestation/paths-sign.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Sign3" rotation={[0, -Math.PI / 2, 0]}>
          <mesh
            name="Cube012"
            castShadow
            receiveShadow
            geometry={nodes.Cube012.geometry}
            material={materials['Dark Wood']}
          />
          <mesh
            name="Cube012_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube012_1.geometry}
            material={materials['Light Wood']}
          />
          <mesh
            name="Cube012_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube012_2.geometry}
            material={materials.Herbs}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/paths-sign.glb')
