/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 crocodile.glb 
Author: fhernand (https://sketchfab.com/fhernand)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nile-crocodile-8a2bf03356c14576b6e54561ea845dc0
Title: Nile Crocodile
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models-3d/biodiversity/crocodile/crocodile.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 450]} scale={0.38}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.tex_u1_v1} />
      </group>
    </group>
  )
}

useGLTF.preload('/models-3d/biodiversity/crocodile/crocodile.glb')
