/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 bee.gltf 
Author: EsiHere (https://sketchfab.com/EsiHere)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bee-low-poly-0416f30815d6422791746b379f802405
Title: Bee (Low Poly)
*/

import React, { useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';



export default function Model(props) {
  const { nodes, materials } = useGLTF('/models-3d/biodiversity/bee/bee.gltf');
  const groupRef = useRef();
  const baseYPosition = -20; // Cambia este valor para ajustar la posición base en Y
  let floatDirection = 0; // Dirección inicial de la flotación

  

  useFrame(() => {
      // Usa la posición base en Y y añade el efecto de flotación
      groupRef.current.position.y = baseYPosition + Math.sin(floatDirection) * 0.5;
      floatDirection += 0.1; 
  });

  return (
    <>
    <group  ref={groupRef} {...props} dispose={null}  >
      <group scale={0.01}>
        <group position={[0,0, 0]} rotation={[-Math.PI / 2, 0, -1]} scale={80}>
          <mesh geometry={nodes.beehive006_Atlas_Alpha_0.geometry} material={materials.Atlas_Alpha} />
          <mesh geometry={nodes.beehive006_Atlas_0.geometry} material={materials.Atlas} />
          <mesh geometry={nodes.beehive006_Atlas_Shiny_0.geometry} material={materials.Atlas_Shiny} />
        </group>
      </group>
    </group>
    
    </>
  );
}

useGLTF.preload('/models-3d/biodiversity/bee/bee.gltf');