/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 bee.gltf 
Author: EsiHere (https://sketchfab.com/EsiHere)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bee-low-poly-0416f30815d6422791746b379f802405
Title: Bee (Low Poly)
*/

import React, {useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
  const meshRef = useRef(); // Referencia al objeto 3D
  let time = 0;
  const { nodes, materials } = useGLTF('/models-3d/biodiversity/bee/bee.gltf')

  useFrame((state, delta) => {
    time += delta;
    meshRef.current.position.z = Math.sin(time) * 0.5; // Movimiento vertical suave
  });

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0,70, 0]} rotation={[-Math.PI / 2, 0, -1]} scale={5}>
        <group ref={meshRef}>
          <mesh geometry={nodes.beehive006_Atlas_Alpha_0.geometry} material={materials.Atlas_Alpha} />
          <mesh geometry={nodes.beehive006_Atlas_0.geometry} material={materials.Atlas} />
          <mesh geometry={nodes.beehive006_Atlas_Shiny_0.geometry} material={materials.Atlas_Shiny} />
        </group>  
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/src/r3f/biodiversity/bee/bee.gltf')
