/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 orchid.glb 
Author: Rigsters (https://sketchfab.com/rigsters)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/orchid-ed453cd6b12f4dfa8d4f3dcf68c97cf1
Title: Orchid
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models-3d/biodiversity/orchid/orchid.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.defaultMat} position={[0,0,0]} rotation={[-1.567, 1.444, -1.478]} scale={0.2} />
    </group>
  )
}

useGLTF.preload('/models-3d/biodiversity/orchid/orchid.glb')
