/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 orchid.glb 
Author: fakefurfetishferre (https://sketchfab.com/fakefurfetishferre)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/orchid-6e6e2ac8986e4fc1bb7c046208e2dacd
Title: Orchid
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models-3d/biodiversity/orchid/orchid.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-20, -3.5, 40]} rotation={[-Math.PI / 2, 0, 0]} scale={0.08}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.FrontColor} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Material__1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Material__1} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Material__1} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Material__1} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Material__1} />
      </group>
    </group>
  )
}

useGLTF.preload('/models-3d/biodiversity/orchid/orchid.glb')
