/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 condor.glb 
Author: ingdearco (https://sketchfab.com/ingdearco)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/condor-edf9faac29be4af98a6adc08952e5420
Title: Condor
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models-3d/biodiversity/condor/condor.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['condor001_Material_#95_0'].geometry} material={materials.Material_95} rotation={[-Math.PI / 2, 0, 200]} scale={0.01}/>
    </group>
  )
}

useGLTF.preload('/models-3d/biodiversity/condor/condor.glb')
