/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function LittleWorld(props) {
  const worldRef = useRef();

  useFrame((state, delta) => {
    worldRef.current.rotation.y += 0.5 * delta;
  });


  const { nodes, materials } = useGLTF('/models-3d/homepage/earth.glb')
  return (
    <group ref={worldRef} scale={2} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sphere" rotation={[-3.138, 0.873, 3.14]}>
          <mesh
            name="Sphere002"
            geometry={nodes.Sphere002.geometry}
            material={materials['Material.009']}
          />
          <mesh
            name="Sphere002_1"
            geometry={nodes.Sphere002_1.geometry}
            material={materials['Material.008']}
          />
          <mesh
            name="Sphere002_2"
            geometry={nodes.Sphere002_2.geometry}
            material={materials['Material.010']}
          />
          <mesh
            name="Sphere002_3"
            geometry={nodes.Sphere002_3.geometry}
            material={materials['Material.005']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models-3d/homepage/earth.glb')

export default LittleWorld