/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 butterflies2.glb 
Author: bestgamekits (https://sketchfab.com/bestgamekits)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/12-animated-butterflies-8ca3b9aa82694e6b8bc53a69b4529539
Title: 12 Animated butterflies
*/

import React, { useEffect, useRef } from 'react';
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models-3d/biodiversity/butterflies/butterflies2.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    // Reproduce todas las animaciones disponibles
    if (actions) {
      Object.values(actions).forEach(action => action.play());
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.005}>
          <group name="a9eb06653d904b9ca3e3dc842d491c7dfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="group1" scale={6.476}>
                </group>
                <group name="group2">
                  <group name="Object_34">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_84" />
                    <group name="Object_86" />
                    <group name="Object_88" />
                    <group name="Object_90" />
                    <group name="Object_92" />
                    <group name="Object_94" />
                    <skinnedMesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials.B_6_M} skeleton={nodes.Object_85.skeleton} />
                    <skinnedMesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.B_6_M} skeleton={nodes.Object_87.skeleton} />
                    <skinnedMesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials.B_6_M} skeleton={nodes.Object_89.skeleton} />
                    <skinnedMesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.B_6_M} skeleton={nodes.Object_91.skeleton} />
                    <skinnedMesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.B_6_M} skeleton={nodes.Object_93.skeleton} />
                    <skinnedMesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials.B_6_M} skeleton={nodes.Object_95.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models-3d/biodiversity/butterflies/butterflies2.glb')
