/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 wolf.glb 
Author: SDPM Esare (https://sketchfab.com/sdpm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/italian-white-wolf-1de9441cb0744c0d8459ce957b8d0a57
Title: Italian White Wolf
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models-3d/biodiversity/wolf/wolf.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material} position={[0, -0.034, 0.39]} rotation={[0,1,0]} scale={0.09} />
    </group>
  )
}

useGLTF.preload('/models-3d/biodiversity/wolf/wolf.glb')
